const opt = [
    {
      "nomor": 1,
      "soal": "Kamu tau kan kalau deadline untuk setoran hafalan adalah saat Ujian Madrasah? Nah, wali kelasmu saat ini sedang membuka setoran hafalan. Kamu hafal surat yang belum kamu setorkan, namun hanya setengahnya",
      "pilihan1": "Setorkan setengahnya",
      "pendidikan1": 1,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Tunggu hafal semua",
      "pendidikan2": 0,
      "sosial2": 1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 2,
      "soal": "Untuk hafalan, kamu membutuhkan buku setoran hafalan. Kamu kehilangan buku setoran hafalan sejak 1 tahun yang lalu. Untuk memegang buku setoran hafalan itu, kamu harus membelinya di Koperasi Siswa. Harganya Rp. 10.000",
      "pilihan1": "Beli",
      "pendidikan1": 2,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": -1,
      "pilihan2": "Tidak beli",
      "pendidikan2": -2,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 1
    },
    {
      "nomor": 3,
      "soal": "Besok akan ada ujian SKI. Kamu diajak temanmu untuk main bareng di game Free Fire",
      "pilihan1": "Invite aku ya!",
      "pendidikan1": -1,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Maaf, aku gabisa",
      "pendidikan2": 1,
      "sosial2": -1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 4,
      "soal": "Kamu melihat temanmu terjatuh karena tidak mengikat tali sepatu dengan benar dan mendarat di genangan air",
      "pilihan1": "Menolongnya",
      "pendidikan1": 1,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": 0,
      "pilihan2": "Menertawakannya",
      "pendidikan2": -1,
      "sosial2": -1,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 5,
      "soal": "Besok akan ada ujian akhir kelas. Temanmu mengajakmu untuk pergi ke Solaria. Dia akan membayar semua menunya",
      "pilihan1": "Aku ikut",
      "pendidikan1": -2,
      "sosial1": 2,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Tidak, aku harus belajar",
      "pendidikan2": 2,
      "sosial2": -2,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 6,
      "soal": "Pada saat ulangan, tiba-tiba kamu menemukan soal yang jelas tidak dapat kamu jawab. Dengan jiwa penyontek handal, kamu mencoba untuk mencari soal tersebut di google. Sayangnya, soal tersebut adalah soal yang dibuat secara original oleh guru",
      "pilihan1": "Cap cip cup",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": 0,
      "pilihan2": "Tanya temen",
      "pendidikan2": 1,
      "sosial2": 1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 7,
      "soal": "Dalam perjalanannya ke Bali, kamu menemukan sebuah sesajen. Sesajen itu berisikan manisan",
      "pilihan1": "Lewati",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Ambil permennya",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": -10,
      "ekonomi2": 0
    },
    {
      "nomor": 8,
      "soal": "Bis masih berhenti selama 5 menit. Bis ini bisa jalan kapan saja. Di seberang kamu terdapat Indomaret dan kamu ingin membeli 2 botol air mineral",
      "pilihan1": "Gaskan, speedrun!",
      "pendidikan1": -1,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": -1,
      "pilihan2": "Sebaiknya jangan terlalu gegabah",
      "pendidikan2": 1,
      "sosial2": -1,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 9,
      "soal": "Pada Jam 5 sore, di sebuah pantai bali, kamu melihat seorang wanita yang menggunakan bikini berwarna merah muda. Ia berjalan melewatimu. Tampaknya tidak memiliki uang untuk membeli kain",
      "pilihan1": "Biarkan",
      "pendidikan1": 1,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Hello, my name is {name}",
      "pendidikan2": -1,
      "sosial2": 1,
      "kesehatan2": 1,
      "ekonomi2": 0
    },
    {
      "nomor": 10,
      "soal": "Pertanyaan ini menggunakan sudut pandang cowok. Hotel itu menyediakan kolam renang. Kolam renang itu layak untuk dicoba. Kamu punya tambahan celana, namun tidak membawa baju renang. Kamu meyakini bahwa aurat cowok adalah dibawah pusar dan diatas lutut",
      "pilihan1": "Batalkan agenda",
      "pendidikan1": 1,
      "sosial1": -1,
      "kesehatan1": -1,
      "ekonomi1": 0,
      "pilihan2": "Apa susahnya Shalat Taubat",
      "pendidikan2": -1,
      "sosial2": 1,
      "kesehatan2": 1,
      "ekonomi2": 0
    },
    {
      "nomor": 11,
      "soal": "Pada Jam 3 pagi, kamu mendengarkan bel 38 kali setiap 10 menit",
      "pilihan1": "Anggep aja soundtrack hotel",
      "pendidikan1": 1,
      "sosial1": 1,
      "kesehatan1": -2,
      "ekonomi1": 0,
      "pilihan2": "Harus ditelusuri pelakunya",
      "pendidikan2": -1,
      "sosial2": -1,
      "kesehatan2": 2,
      "ekonomi2": 0
    },
    {
      "nomor": 12,
      "soal": "Kamu ditawarkan oleh ‘dia’ untuk membeli pie susu seharga 22k/10pcs. Kamu telah mencoba pie susu itu dan rasanya sangat lezat!",
      "pilihan1": "Beli, suka rasanya",
      "pendidikan1": 1,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": -3,
      "pilihan2": "Tidak beli, harga tidak sesuai pelajar",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    }
   ]