const opt = [
    {
      "nomor": 1,
      "soal": "Waduh, kamu lupa lagi Ujian Madrasah untuk kelas 9A akan dilaksanakan di kelas mana",
      "pilihan1": "Dekat masjid",
      "pendidikan1": 1,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Dekat koperasi siswa",
      "pendidikan2": -1,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 2,
      "soal": "Kamu menyadari bahwa Ujian Madrasah merupakan kolaborasi kelas 7, 8, dan 9. Sayangnya, buku kelas 7 dan 8 telah dijual kiloan karena berpikir bahwa buku itu tidak akan dipakai lagi",
      "pilihan1": "Cari rangkuman di internet",
      "pendidikan1": 1,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Materi kelas rendah itu saya juga hafal",
      "pendidikan2": -1,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 3,
      "soal": "Kamu tinggal menamatkan Surat An-Naba dan setelah itu kamu akan mendapatkan kartu kuning bukti menyelesaikan hafalan. Kamu sudah hafal surat itu, namun kamu terlalu grogi untuk maju karena tidak ada yang maju",
      "pilihan1": "Maju langsung",
      "pendidikan1": 1,
      "sosial1": -1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Mungkin besok saja",
      "pendidikan2": -1,
      "sosial2": 1,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 4,
      "soal": "Kamu menemani temanmu untuk membeli buku setoran hafalan. Kamu terkejut melihat harganya, karena sebelumnya buku setoran hafalan yang sama dijual kepadamu dengan harga yang lebih mahal",
      "pilihan1": "Laksanakan protes",
      "pendidikan1": -2,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": 1,
      "pilihan2": "Cukup beritahu ke teman",
      "pendidikan2": 0,
      "sosial2": 1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 5,
      "soal": "War Ujian Madrasah dalam bentuk tulis telah selesai. Kamu diajak oleh temanmu untuk self-reward dengan cara minum-minum",
      "pilihan1": "Tidak akan",
      "pendidikan1": 1,
      "sosial1": -1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Nanti aku akan darang",
      "pendidikan2": -1,
      "sosial2": 1,
      "kesehatan2": -1,
      "ekonomi2": -1
    },
    {
      "nomor": 6,
      "soal": "Kamu diinstruksikan untuk masuk, namun sebenarnya tidak ada apa-apa. Sepertinya tidak akan ada konsekuensi kalau tidak masuk",
      "pilihan1": "Enggak harus masuk",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": 1,
      "ekonomi1": 0,
      "pilihan2": "Enggak, harus masuk",
      "pendidikan2": 0,
      "sosial2": 1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 7,
      "soal": "Pada ujian praktik Seni Budaya, diinstruksikan untuk melukis tembok di kantin dengan tema makanan sehat atau kantin sehat. Satu kelas memiliki nilai yang sama. Kamu tidak memiliki keahlian dalam melukis",
      "pilihan1": "Ikut berkontribusi pada ide",
      "pendidikan1": 1,
      "sosial1": -1,
      "kesehatan1": -1,
      "ekonomi1": 0,
      "pilihan2": "Paksakan melukis",
      "pendidikan2": -1,
      "sosial2": 1,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 8,
      "soal": "Karena ingin mengambil jalan pintas dan ingin lebih cepat datang ke Kelas, kamu mencoba untuk memanjat pagar. Seusai memanjat pagar, kamu kehilangan keseimbangan dan secara tidak sengaja menabrak seseorang. Ia menyalahkanmu dan menyusun cerita seolah-olah kamu sengaja melakukannya",
      "pilihan1": "Meminta maaf",
      "pendidikan1": 1,
      "sosial1": 1,
      "kesehatan1": -2,
      "ekonomi1": 0,
      "pilihan2": "Mengatakan \"kamu tidak lihat situasinya hah?\"",
      "pendidikan2": -1,
      "sosial2": -1,
      "kesehatan2": 2,
      "ekonomi2": 0
    },
    {
      "nomor": 9,
      "soal": "Hari ini adalah hari terakhir untuk pendidikan formal. Mengenakan baju olahraga yang dipeniti nomor peserta, kamu diletakkan di lapangan utama untuk melakukan Ujian Praktik olahraga di hari yang cerah pada jam 07:30, yang mana mengharuskanmu untuk lari sejauh 3,6km",
      "pilihan1": "Lari pelan saja",
      "pendidikan1": 1,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Lari cepat all in 100%",
      "pendidikan2": 2,
      "sosial2": 0,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 10,
      "soal": "Setiap siswa diperintahkan untuk melakukan urunan 7 ribu, untuk membayar videografer",
      "pilihan1": "Bayar urunan",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": -1,
      "pilihan2": "Tunda pembayaran",
      "pendidikan2": 0,
      "sosial2": -1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 11,
      "soal": "Salah satu teman satu angkatanmu (lawan jenis) mengatakan bahwa dia memiliki crush dengan kamu. Namun, kamu memiliki crush kepada orang selain dia",
      "pilihan1": "Terima",
      "pendidikan1": -2,
      "sosial1": 1,
      "kesehatan1": -2,
      "ekonomi1": -2,
      "pilihan2": "Kita temenan aja",
      "pendidikan2": 0,
      "sosial2": -2,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 12,
      "soal": "31 Mei. Kamu diajak untuk melakukan videografi. Kamu berhasil. Selamat tinggal, temanku",
      "pilihan1": "Bye",
      "pendidikan1": 6,
      "sosial1": 6,
      "kesehatan1": 6,
      "ekonomi1": 6,
      "pilihan2": "Bye",
      "pendidikan2": 6,
      "sosial2": 6,
      "kesehatan2": 6,
      "ekonomi2": 6
    }
   ]