const opt = [
    {
      "nomor": 1,
      "soal": "Tahun baru, resolusi baru, harapan baru. Seluruh jiwamu diwarnai energi positif",
      "pilihan1": "Hore!",
      "pendidikan1": 1,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": 1,
      "pilihan2": "Yippeee!",
      "pendidikan2": 1,
      "sosial2": 1,
      "kesehatan2": 1,
      "ekonomi2": 1
    },
    {
      "nomor": 2,
      "soal": "2 Januari. Kamu di-invite untuk pergi ke rumah teman dengan tujuan makan bersama-sama besok",
      "pilihan1": "Count me in",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Count me out",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 3,
      "soal": "Ada yang aneh di buku Kelas 9 Semester 2. Lebih mudah dan tipis",
      "pilihan1": "Kalau gitu Alhamdulillah",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Mencurigakan",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 4,
      "soal": "Kamu melihat Ketua Kelas mengirimkan agenda kegiatan untuk semester 2 ini",
      "pilihan1": "Jangan dibuka",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Aku penasaran isinya apa",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 5,
      "soal": "Jadwal ekstrakurikulermu bertabrakan dengan jadwal belajarmu",
      "pilihan1": "Ikuti jadwal ekstra",
      "pendidikan1": -1,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Ikuti jadwal belajar",
      "pendidikan2": 1,
      "sosial2": -1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 6,
      "soal": "Kamu ditawari les bimbel dengan biaya yang mahal",
      "pilihan1": "Terima",
      "pendidikan1": 2,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": -2,
      "pilihan2": "Tolak",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 7,
      "soal": "Kamu melihat temanmu yang suka merendahkan kamu kesulitan mengerjakan tugas",
      "pilihan1": "Akan kubantu",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": 0,
      "pilihan2": "Hanya jika ia minta maaf",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 2,
      "ekonomi2": 0
    },
    {
      "nomor": 8,
      "soal": "Ada sangat banyak tugas yang harus dikerjakan besok! Kamu dapat mengerjakannya semuanya, namun jam tidurmu akan rusak untuk sementara waktu",
      "pilihan1": "Begadang jangan begadang",
      "pendidikan1": -1,
      "sosial1": 0,
      "kesehatan1": 1,
      "ekonomi1": 0,
      "pilihan2": "Begadang boleh saja asal ada perlunya",
      "pendidikan2": 1,
      "sosial2": 0,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 9,
      "soal": "Kamu ditawari bolos sekolah selama 3 hari",
      "pilihan1": "Ikuti tawaran",
      "pendidikan1": -1,
      "sosial1": -1,
      "kesehatan1": -1,
      "ekonomi1": -1,
      "pilihan2": "Menolak dengan halus",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 10,
      "soal": "Kamu mendapatkan tugas kelompok yang anggotanya tidak kooperatif",
      "pilihan1": "Akan kukerjakan sendiri",
      "pendidikan1": 1,
      "sosial1": 0,
      "kesehatan1": -2,
      "ekonomi1": 0,
      "pilihan2": "Akan kutegur mereka",
      "pendidikan2": 1,
      "sosial2": -2,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 11,
      "soal": "Tawaran dukun: Aib kamu akan terbongkar, namun uang dan kesehatan kamu akan meningkat",
      "pilihan1": "Terima",
      "pendidikan1": 0,
      "sosial1": -2,
      "kesehatan1": 1,
      "ekonomi1": 1,
      "pilihan2": "Tolak",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 12,
      "soal": "Tawaran dukun: Dengan membayar sedikit uang, kau akan mendapatkan teman dan kesehatan",
      "pilihan1": "Terima",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": -2,
      "pilihan2": "Tolak",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    }
   ]