var opt = [
    {
        "nomor": 1,
        "soal": "Sepulang sekolah, kamu ditagih oleh bendahara ekstrakurikuler untuk membayar kas",
        "pilihan1": "Bayar",
        "pendidikan1": 0,
        "sosial1": 1,
        "kesehatan1": -1,
        "ekonomi1": -1,
        "pilihan2": "Nanti aja…",
        "pendidikan2": 0,
        "sosial2": -1,
        "kesehatan2": 0,
        "ekonomi2": 1
    },
    {
        "nomor": 2,
        "soal": "Kamu melihat temanmu yang sering membullymu sedang kesulitan mengerjakan tugas",
        "pilihan1": "Membantunya",
        "pendidikan1": 0,
        "sosial1": 1,
        "kesehatan1": 1,
        "ekonomi1": 0,
        "pilihan2": "Hanya jika ia bersedia minta maaf",
        "pendidikan2": 0,
        "sosial2": 0,
        "kesehatan2": 2,
        "ekonomi2": 0
    },
    {
        "nomor": 3,
        "soal": "Kamu mendapatkan uang saku mingguan",
        "pilihan1": "Hore!",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 0,
        "ekonomi1": 2,
        "pilihan2": "Sedekahkan saja semua",
        "pendidikan2": 0,
        "sosial2": 2,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 4,
        "soal": "Kamu diminta untuk menjadi ketua kelas",
        "pilihan1": "Tolak",
        "pendidikan1": 0,
        "sosial1": -2,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Terima",
        "pendidikan2": 0,
        "sosial2": 2,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 5,
        "soal": "Kamu ditawari oleh orang yang dapat dipercaya untuk menjadi mentormu. Tentunya ini sangatlah mahal bagi pelajar sepertimu",
        "pilihan1": "Aku menolak",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Boleh",
        "pendidikan2": 1,
        "sosial2": 1,
        "kesehatan2": 1,
        "ekonomi2": -3
    },
    {
        "nomor": 6,
        "soal": "Kamu ingin ikut kegiatan ekstrakurikuler, tapi jadwalnya bertabrakan dengan jadwal belajar kamu dan besok akan ujian",
        "pilihan1": "Ikuti ekstrakurikuler",
        "pendidikan1": -2,
        "sosial1": 2,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Ikuti jadwal belajar",
        "pendidikan2": 2,
        "sosial2": -2,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 7,
        "soal": "Penawaran: Kamu ditawari untuk masuk les dengan biaya mahal",
        "pilihan1": "Menolak",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Menerima",
        "pendidikan2": 2,
        "sosial2": 0,
        "kesehatan2": 0,
        "ekonomi2": -2
    },
    {
        "nomor": 8,
        "soal": "Ada sangat banyak tugas yang harus dikumpulkan besok! Kamu bisa mengerjakan semuanya, tapi harus begadang",
        "pilihan1": "Begadang boleh saja kalau ada perlunya",
        "pendidikan1": 1,
        "sosial1": 0,
        "kesehatan1": -1,
        "ekonomi1": 0,
        "pilihan2": "Begadang jangan begadang",
        "pendidikan2": -1,
        "sosial2": 0,
        "kesehatan2": 1,
        "ekonomi2": 0
    },
    {
        "nomor": 9,
        "soal": "Teman kamu menawarkanmu sebuah rokok",
        "pilihan1": "Sebaiknya jangan",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 1,
        "ekonomi1": 0,
        "pilihan2": "Mengikuti tawarannya",
        "pendidikan2": 0,
        "sosial2": 1,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 10,
        "soal": "Kamu memiliki kesempatan untuk mengikuti lomba akademik mewakili madrasah",
        "pilihan1": "Ambil kesempatannya",
        "pendidikan1": 1,
        "sosial1": 1,
        "kesehatan1": -1,
        "ekonomi1": -1,
        "pilihan2": "Kasih ke orang lain",
        "pendidikan2": -1,
        "sosial2": -1,
        "kesehatan2": -1,
        "ekonomi2": -1
    },
    {
        "nomor": 11,
        "soal": "Saat istirahat, kamu berkeinginan untuk membeli jajan di Koperasi Siswa",
        "pilihan1": "Boleh",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 0,
        "ekonomi1": -1,
        "pilihan2": "Jangan",
        "pendidikan2": 0,
        "sosial2": 0,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 12,
        "soal": "Kamu ditawari untuk bolos sekolah selama 3 hari",
        "pilihan1": "Boleh juga",
        "pendidikan1": -1,
        "sosial1": -1,
        "kesehatan1": 1,
        "ekonomi1": 1,
        "pilihan2": "Menolak dengan halus",
        "pendidikan2": 0,
        "sosial2": 0,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 13,
        "soal": "Teman lawan jenis mengatakan \"Maukah kau menjadi pacarku?\"",
        "pilihan1": "Mau dong",
        "pendidikan1": -2,
        "sosial1": 1,
        "kesehatan1": -2,
        "ekonomi1": -2,
        "pilihan2": "Nice try ;)",
        "pendidikan2": 0,
        "sosial2": -2,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 14,
        "soal": "Kamu mendapat tugas kelompok yang anggotanya kurang kooperatif",
        "pilihan1": "Menegur",
        "pendidikan1": 1,
        "sosial1": -2,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Aku lakukan semuanya sendiri",
        "pendidikan2": 1,
        "sosial2": 0,
        "kesehatan2": -2,
        "ekonomi2": 0
    },
    {
        "nomor": 15,
        "soal": "Tawaran Dukun: Aib terbesar kamu akan terbongkar, namun kamu mendapatkan uang dan kesehatan",
        "pilihan1": "Setuju",
        "pendidikan1": 0,
        "sosial1": -2,
        "kesehatan1": 1,
        "ekonomi1": 1,
        "pilihan2": "Tidak setuju",
        "pendidikan2": 0,
        "sosial2": 0,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 16,
        "soal": "Besok akan ada ujian Fikih. Temanmu mengajakmu mabar Free Fire",
        "pilihan1": "Invite aku ya",
        "pendidikan1": -1,
        "sosial1": 1,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Maaf, saya mau belajar buat besok",
        "pendidikan2": 1,
        "sosial2": -1,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 17,
        "soal": "Kamu mendapatkan nilai buruk di pelajaran yang kamu benci",
        "pilihan1": "Belajar lebih giat",
        "pendidikan1": 2,
        "sosial1": 0,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Angkat bendera putih (menyerah)",
        "pendidikan2": -2,
        "sosial2": -1,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 18,
        "soal": "Kamu mendapatkan uang saku mingguan",
        "pilihan1": "Hore!",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 0,
        "ekonomi1": 2,
        "pilihan2": "Gunakan untuk membeli buku baru",
        "pendidikan2": 1,
        "sosial2": 0,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 19,
        "soal": "Kamu menemukan sisi tergelap teman terdekatmu setelah ia curhat. Kamu berjanji akan membiarkan ia memenggal kepalamu jika kamu cepu",
        "pilihan1": "Sebarkan",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": -10,
        "ekonomi1": 0,
        "pilihan2": "Simpan rahasia itu",
        "pendidikan2": 0,
        "sosial2": 1,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 20,
        "soal": "Ditawari kerja part-time tapi bisa memotong waktu belajar (magang tapi dibayar)",
        "pilihan1": "Oke",
        "pendidikan1": -1,
        "sosial1": 0,
        "kesehatan1": -1,
        "ekonomi1": 2,
        "pilihan2": "Nanti aja kali",
        "pendidikan2": 1,
        "sosial2": 0,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 21,
        "soal": "Ada pelajaran yang kamu sukai, namun teman sebangkumu selalu mengganggu dan membuatmu tidak bisa fokus",
        "pilihan1": "Menegur",
        "pendidikan1": 1,
        "sosial1": 1,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Pindah tempat duduk",
        "pendidikan2": 1,
        "sosial2": -1,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 22,
        "soal": "Kamu terlambat dan harus mencatat nama di buku. Saat ini, kamu sedang menggunakan baju olahraga",
        "pilihan1": "Catat nama sendiri",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Catat nama orang lain",
        "pendidikan2": -2,
        "sosial2": 2,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 23,
        "soal": "Kamu terlibat dalam kegiatan ekstrakurikuler yang menuntut waktu dan energi",
        "pilihan1": "Resign",
        "pendidikan1": 1,
        "sosial1": -2,
        "kesehatan1": 1,
        "ekonomi1": 0,
        "pilihan2": "Lanjut",
        "pendidikan2": -1,
        "sosial2": 2,
        "kesehatan2": -1,
        "ekonomi2": 0
    },
    {
        "nomor": 24,
        "soal": "Kamu diajak oleh temanmu untuk makan makanan di restoran cepat saji",
        "pilihan1": "Ayo aja gua mah",
        "pendidikan1": 0,
        "sosial1": 2,
        "kesehatan1": -1,
        "ekonomi1": -1,
        "pilihan2": "Nggak dulu",
        "pendidikan2": 0,
        "sosial2": -2,
        "kesehatan2": 1,
        "ekonomi2": 1
    },
    {
        "nomor": 25,
        "soal": "Kamu diminta untuk mengikuti kegiatan ekstrakurikuler yang tidak kamu minati",
        "pilihan1": "Tolong daftarkan namaku",
        "pendidikan1": -1,
        "sosial1": 1,
        "kesehatan1": -1,
        "ekonomi1": -1,
        "pilihan2": "Menolak dengan halus",
        "pendidikan2": 1,
        "sosial2": -1,
        "kesehatan2": 1,
        "ekonomi2": 1
    },
    {
        "nomor": 26,
        "soal": "Tawaran Dukun: Dengan uang yang besar, kamu akan menjadi sangat sehat",
        "pilihan1": "Setuju",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 2,
        "ekonomi1": -2,
        "pilihan2": "Tidak setuju",
        "pendidikan2": 0,
        "sosial2": 0,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 27,
        "soal": "Teman *terdekat* kamu ternyata bandar pornografi!",
        "pilihan1": "Aku minta dong!",
        "pendidikan1": -1,
        "sosial1": 1,
        "kesehatan1": -1,
        "ekonomi1": 0,
        "pilihan2": "Unfriend",
        "pendidikan2": 1,
        "sosial2": -2,
        "kesehatan2": 1,
        "ekonomi2": 0
    },
    {
        "nomor": 28,
        "soal": "Kamu diundang untuk menghadiri bukber pada hari Sabtu malam tapi kamu memiliki ujian penting pada Senin pagi",
        "pilihan1": "Aku belajar",
        "pendidikan1": 2,
        "sosial1": -2,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Aku ikut bukber",
        "pendidikan2": -2,
        "sosial2": 1,
        "kesehatan2": 0,
        "ekonomi2": 0
    },
    {
        "nomor": 29,
        "soal": "Akan ada Ujian Praktek olahraga, yaitu lari 2,4km. Persiapan 1 bulan",
        "pilihan1": "Aku akan melatih tubuhku",
        "pendidikan1": 1,
        "sosial1": 0,
        "kesehatan1": 2,
        "ekonomi1": 0,
        "pilihan2": "Aku tidak akan melatih tubuhku",
        "pendidikan2": -2,
        "sosial2": -1,
        "kesehatan2": -2,
        "ekonomi2": 0
    },
    {
        "nomor": 30,
        "soal": "Tawaran Dukun: Kamu mendapatkan uang besar, tapi skill komunikasi kamu berkurang",
        "pilihan1": "Tidak setuju",
        "pendidikan1": 0,
        "sosial1": 0,
        "kesehatan1": 0,
        "ekonomi1": 0,
        "pilihan2": "Setuju",
        "pendidikan2": 0,
        "sosial2": -2,
        "kesehatan2": 0,
        "ekonomi2": 2
    },
    {
        "nomor": 31,
        "soal": "Kamu akan mengikuti tes olahraga. Kamu merasa tidak percaya diri dengan kemampuanmu dan khawatir kamu akan mendapatkan nilai yang buruk",
        "pilihan1": "Mencoba yang terbaik dalam tes",
        "pendidikan1": 1,
        "sosial1": 1,
        "kesehatan1": 1,
        "ekonomi1": 1,
        "pilihan2": "Membuat alasan tidak masuk besok",
        "pendidikan2": -2,
        "sosial2": -2,
        "kesehatan2": -2,
        "ekonomi2": 0
    }
]