const opt = [
    {
      "nomor": 1,
      "soal": "Ujian Akhir Kelas dilaksanakan pada Bulan Ramadhan",
      "pilihan1": "Yaudah sih",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 1,
      "ekonomi1": 0,
      "pilihan2": "Jangan puasa dulu wkwk",
      "pendidikan2": -1,
      "sosial2": -1,
      "kesehatan2": -1,
      "ekonomi2": -1
    },
    {
      "nomor": 2,
      "soal": "Temanmu meminta jawaban untuk sebagian soal pada Ujian Akhir Kelas ini",
      "pilihan1": "Berikan",
      "pendidikan1": -1,
      "sosial1": 2,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Menolak untuk memberikan",
      "pendidikan2": 1,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 3,
      "soal": "Kamu mendapat uang saku mingguan",
      "pilihan1": "Hore!",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 2,
      "pilihan2": "Gunakan untuk membeli buku baru",
      "pendidikan2": 2,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 4,
      "soal": "Meski sudah sertijab, entah mengapa kamu tetap terlibat dalam kegiatan ekstrakulikuler yang menguras tenaga dan waktu",
      "pilihan1": "Lepas seluruhnya",
      "pendidikan1": 1,
      "sosial1": -1,
      "kesehatan1": -1,
      "ekonomi1": 1,
      "pilihan2": "Lanjut",
      "pendidikan2": -1,
      "sosial2": 1,
      "kesehatan2": 1,
      "ekonomi2": -1
    },
    {
      "nomor": 5,
      "soal": "Guru SKI mengirimkan PowerPoint pada jam 10 malam, dan kamu diinstruksikan untuk menulisnya ke dalam catatan kemudian mengumpulkannya besok. Kamu melihat informasi itu pada jam 5 pagi",
      "pilihan1": "Tulis di catatan",
      "pendidikan1": 1,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Langsung berangkat sekolah",
      "pendidikan2": 0,
      "sosial2": 1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 6,
      "soal": "Pada saat Pondok Ramadhan, kamu melihat anak yang sedang minum es teh pada siang hari. Kamu yakin betul bahwa ia adalah siswa di madrasah ini. Sayangnya, HP kamu telah dikumpulkan",
      "pilihan1": "Menegur",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Laporkan",
      "pendidikan2": 2,
      "sosial2": -1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 7,
      "soal": "Di Pondok Ramadhan, terdapat aturan bahwa setiap agenda kegiatan harus diikuti setiap siswa. Namun, entah kenapa raga kamu tidak ingin pergi ke mushola untuk mengaji kitab kuning",
      "pilihan1": "Ikuti kemauan raga",
      "pendidikan1": -1,
      "sosial1": 2,
      "kesehatan1": -1,
      "ekonomi1": 0,
      "pilihan2": "Ikuti kemauan arwah",
      "pendidikan2": 1,
      "sosial2": 0,
      "kesehatan2": 1,
      "ekonomi2": 0
    },
    {
      "nomor": 8,
      "soal": "Masih dalam konteks Pondok Ramadhan, kamu melihat temanmu menyalakan petasan setelah rangkaian acara selesai",
      "pilihan1": "Bilang kalau itu gaboleh",
      "pendidikan1": 1,
      "sosial1": -1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Urusan orang lain gaboleh ikut campur",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 9,
      "soal": "Hei lihat, libur Ramadhan",
      "pilihan1": "HORE!",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": 2,
      "ekonomi1": 0,
      "pilihan2": "HORE!",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 2,
      "ekonomi2": 0
    },
    {
      "nomor": 10,
      "soal": "Kamu mendengar sisi tergelap temanmu saat ia curhat. Kamu berjanji akan membiarkan ia memenggal kepalamu jika kamu tidak bisa menjaga rahasia",
      "pilihan1": "Tetap menjaga rahasia",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Sebarkan rahasia itu",
      "pendidikan2": 1,
      "sosial2": 1,
      "kesehatan2": -10,
      "ekonomi2": 1
    },
    {
      "nomor": 11,
      "soal": "Kamu terlambat dan harus mencatat nama di buku. Saat ini kamu menggunakan baju olahraga, yang mana tidak akan ada seorang pun yang mengetahui identitasmu apabila tidak mengenalmu",
      "pilihan1": "Pakai nama sendiri",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Pakai nama orang lain",
      "pendidikan2": 2,
      "sosial2": -2,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 12,
      "soal": "Kamu mendapatkan nilai buruk pada pelajaran yang kamu benci",
      "pilihan1": "Belajar lebih giat",
      "pendidikan1": 1,
      "sosial1": 0,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Mengeluarkan bendera putih [menyerah]",
      "pendidikan2": -2,
      "sosial2": 1,
      "kesehatan2": 0,
      "ekonomi2": 0
    }
   ]