const opt = [
    {
      "nomor": 1,
      "soal": "Kelas barumu memiliki banyak debu dan banyak sarang laba-laba. Hari ini, kamu seharusnya membersihkan kelas baru. Namun, ternyata sebagian dari temanmu tidak masuk",
      "pilihan1": "Bersihkan kelas baru",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": 1,
      "ekonomi1": 0,
      "pilihan2": "Tunda minggu depan",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 2,
      "soal": "Classmeeting ini ada bazar. Setiap kelas akan menjual makanan dan minumannya masing-masing. Ini adalah kesempatan sekali setahun!",
      "pilihan1": "Akan kubeli bazar",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": -1,
      "pilihan2": "Akan kumakan sisa jualan kelasku",
      "pendidikan2": 0,
      "sosial2": -1,
      "kesehatan2": 0,
      "ekonomi2": 1
    },
    {
      "nomor": 3,
      "soal": "Pak Ridwan hari ini ulang tahun. Sisihkan sedikit iuran untuk merayakan ulang tahun wali kelas",
      "pilihan1": "Boleh",
      "pendidikan1": 1,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": -1,
      "pilihan2": "Malas",
      "pendidikan2": -1,
      "sosial2": -1,
      "kesehatan2": 0,
      "ekonomi2": 2
    },
    {
      "nomor": 4,
      "soal": "Besok ada Event Muharram, yang akan dilaksanakan sampai waktu Isya",
      "pilihan1": "Ikut",
      "pendidikan1": 1,
      "sosial1": 1,
      "kesehatan1": -1,
      "ekonomi1": 0,
      "pilihan2": "Ada acara keluarga",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 5,
      "soal": "Perubahan Jadwal sekolah. Masuk jam 06.30 dan pulang jam 14.00",
      "pilihan1": "Sial",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": -1,
      "ekonomi1": 0,
      "pilihan2": "Ugh",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": -1,
      "ekonomi2": 0
    },
    {
      "nomor": 6,
      "soal": "Perubahan Aturan Sekolah. Sekarang menjadi lebih ketat",
      "pilihan1": "Sial",
      "pendidikan1": 0,
      "sosial1": -1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Ugh",
      "pendidikan2": 0,
      "sosial2": -1,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 7,
      "soal": "Besok akan ada event makan bersama. Tidak ada pelajaran lain",
      "pilihan1": "Masuk",
      "pendidikan1": 1,
      "sosial1": 1,
      "kesehatan1": -1,
      "ekonomi1": -1,
      "pilihan2": "Maaf, ada acara keluarga",
      "pendidikan2": -2,
      "sosial2": 0,
      "kesehatan2": 1,
      "ekonomi2": 1
    },
    {
      "nomor": 8,
      "soal": "Hari ini ada event makan bersama. Di tengah makan, ternyata ada makananmu yang jatuh ke tanah",
      "pilihan1": "Ambil dan makan",
      "pendidikan1": 0,
      "sosial1": 0,
      "kesehatan1": -1,
      "ekonomi1": 0,
      "pilihan2": "Buang",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 9,
      "soal": "Pada event makan bersama, tiba-tiba botol minum kamu tersenggol, jatuh, dan menumpahkan air. Air itu membuat makanan temanmu memiliki kuah",
      "pilihan1": "Minta maaf",
      "pendidikan1": 0,
      "sosial1": -2,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Minta maaf + Ganti rugi",
      "pendidikan2": 0,
      "sosial2": 1,
      "kesehatan2": 0,
      "ekonomi2": -2
    },
    {
      "nomor": 10,
      "soal": "Kamu mendengar sebuah pidato dari Pak Saiful pada saat makan bersama. Kamu tidak terlalu memperhatikan isi pidatonya. Tiba-tiba, sekelompok orang bertepuk tangan",
      "pilihan1": "Ikut bertepuk tangan",
      "pendidikan1": -1,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": 0,
      "pilihan2": "Tidak ikut-ikutan",
      "pendidikan2": 0,
      "sosial2": 0,
      "kesehatan2": 0,
      "ekonomi2": 0
    },
    {
      "nomor": 11,
      "soal": "Minggu depan akan ada pawai. Siswa lain mengutarakan pendapat untuk memakai dress code berwarna hitam. Baginya, warna hitam memberi kesan elegan. Bagimu, warna hitam membuat badan terasa panas dan gerah",
      "pilihan1": "Setuju hitam",
      "pendidikan1": 1,
      "sosial1": -1,
      "kesehatan1": -1,
      "ekonomi1": 0,
      "pilihan2": "Setuju putih",
      "pendidikan2": -1,
      "sosial2": 1,
      "kesehatan2": 1,
      "ekonomi2": 0
    },
    {
      "nomor": 12,
      "soal": "Hari ini kamu harus membayar kas",
      "pilihan1": "Oke",
      "pendidikan1": 0,
      "sosial1": 1,
      "kesehatan1": 0,
      "ekonomi1": -1,
      "pilihan2": "Minggu depan",
      "pendidikan2": 0,
      "sosial2": -1,
      "kesehatan2": 0,
      "ekonomi2": -1
    }
   ]